import type {
  AiResult,
  AnnotationRevision,
  AnnotationTask,
  AuditEvent,
  DashboardSummary,
  MeResponse,
  ProjectSummary,
  RiskAlert,
  RiskSignal,
  RiskStrategy,
  SourceAsset,
  WorkflowRun,
} from "@/lib/contracts";

const organizationId = "org_nexus";

export const meResponse: MeResponse = {
  user: {
    id: "user_annotator_1",
    email: "lin.chen@nexus.example",
    display_name: "Lin Chen",
    status: "active",
  },
  organization: {
    id: organizationId,
    slug: "nexus-ops",
    name: "Nexus Ops",
    status: "active",
  },
  organization_role: "project_manager",
  project_memberships: [
    {
      project_id: "proj_atlas",
      project_code: "ATLAS",
      project_name: "Atlas Audio Safety",
      project_role: "project_manager",
      status: "active",
    },
    {
      project_id: "proj_beacon",
      project_code: "BEACON",
      project_name: "Beacon Vision QA",
      project_role: "reviewer",
      status: "active",
    },
  ],
  effective_permissions: [
    "projects.read",
    "annotation.read",
    "annotation.review",
    "risk.read",
    "workflow_runs.read",
  ],
};

export const projectSummaries: ProjectSummary[] = [
  {
    id: "proj_atlas",
    organization_id: organizationId,
    code: "ATLAS",
    name: "Atlas Audio Safety",
    description:
      "Audio and image annotation program for PPE compliance and field safety evidence.",
    status: "active",
    owner_user_id: "user_pm_1",
    settings: {
      review_mode: "human_required",
      default_priority: 90,
    },
    counts: {
      annotation_queue: 12,
      risk_queue: 3,
      active_workflow_runs: 4,
      waiting_for_human_runs: 2,
    },
  },
  {
    id: "proj_beacon",
    organization_id: organizationId,
    code: "BEACON",
    name: "Beacon Vision QA",
    description:
      "Image and video quality pipeline for defect review and release readiness.",
    status: "watch",
    owner_user_id: "user_pm_2",
    settings: {
      review_mode: "reviewer_optional",
      default_priority: 60,
    },
    counts: {
      annotation_queue: 7,
      risk_queue: 2,
      active_workflow_runs: 2,
      waiting_for_human_runs: 1,
    },
  },
];

export const sourceAssets: SourceAsset[] = [
  {
    id: "asset_atlas_img_1",
    project_id: "proj_atlas",
    dataset_id: "dataset_atlas_ops",
    asset_kind: "image",
    uri: "https://example.com/assets/atlas/ppe-001.jpg",
    storage_key: "atlas/ppe-001.jpg",
    mime_type: "image/jpeg",
    checksum: "sha256:atlas001",
    duration_ms: null,
    width_px: 1920,
    height_px: 1080,
    frame_rate: null,
    transcript: null,
    metadata: {
      site: "plant-7",
      shift: "night",
    },
  },
  {
    id: "asset_atlas_vid_1",
    project_id: "proj_atlas",
    dataset_id: "dataset_atlas_ops",
    asset_kind: "video",
    uri: "https://example.com/assets/atlas/loading-bay-clip.mp4",
    storage_key: "atlas/loading-bay-clip.mp4",
    mime_type: "video/mp4",
    checksum: "sha256:atlasvid001",
    duration_ms: 92000,
    width_px: 1280,
    height_px: 720,
    frame_rate: 29.97,
    transcript: null,
    metadata: {
      camera: "loading-bay-3",
      weather: "rain",
    },
  },
  {
    id: "asset_beacon_audio_1",
    project_id: "proj_beacon",
    dataset_id: "dataset_beacon_support",
    asset_kind: "audio",
    uri: "https://example.com/assets/beacon/call-441.wav",
    storage_key: "beacon/call-441.wav",
    mime_type: "audio/wav",
    checksum: "sha256:beaconaud001",
    duration_ms: 186000,
    width_px: null,
    height_px: null,
    frame_rate: null,
    transcript: "Customer reports camera blur during low-light verification.",
    metadata: {
      channel: "support",
      language: "en",
    },
  },
];

export const annotationTasks: AnnotationTask[] = [
  {
    id: "task_atlas_1",
    project_id: "proj_atlas",
    dataset_id: "dataset_atlas_ops",
    source_asset_id: "asset_atlas_img_1",
    task_type: "ppe_detection",
    status: "in_progress",
    priority: 90,
    assigned_to_user_id: "user_annotator_1",
    reviewer_user_id: "user_reviewer_1",
    created_by_user_id: "user_pm_1",
    current_workflow_run_id: "run_ann_1",
    latest_ai_result_id: "ai_ann_1",
    annotation_schema: {
      labels: ["helmet", "vest", "goggles", "gloves"],
      required_regions: true,
    },
    input_payload: {
      brief: "Verify PPE coverage for visible workers.",
    },
    output_payload: {
      draft_labels: ["helmet", "vest"],
      reviewer_note: "Need confirmation on goggles.",
    },
    claimed_at: "2026-03-18T08:10:00Z",
    due_at: "2026-03-18T16:30:00Z",
    submitted_at: null,
    reviewed_at: null,
    completed_at: null,
  },
  {
    id: "task_atlas_2",
    project_id: "proj_atlas",
    dataset_id: "dataset_atlas_ops",
    source_asset_id: "asset_atlas_vid_1",
    task_type: "unsafe_motion_review",
    status: "queued",
    priority: 60,
    assigned_to_user_id: "user_annotator_2",
    reviewer_user_id: "user_reviewer_1",
    created_by_user_id: "user_pm_1",
    current_workflow_run_id: "run_ann_2",
    latest_ai_result_id: null,
    annotation_schema: {
      labels: ["forklift", "pedestrian", "near_miss"],
      segment_timeline: true,
    },
    input_payload: {
      brief: "Tag near-miss windows and affected actors.",
    },
    output_payload: {},
    claimed_at: null,
    due_at: "2026-03-19T03:00:00Z",
    submitted_at: null,
    reviewed_at: null,
    completed_at: null,
  },
  {
    id: "task_beacon_1",
    project_id: "proj_beacon",
    dataset_id: "dataset_beacon_support",
    source_asset_id: "asset_beacon_audio_1",
    task_type: "issue_summary",
    status: "submitted",
    priority: 60,
    assigned_to_user_id: "user_annotator_1",
    reviewer_user_id: "user_reviewer_2",
    created_by_user_id: "user_pm_2",
    current_workflow_run_id: "run_ann_3",
    latest_ai_result_id: "ai_ann_2",
    annotation_schema: {
      labels: ["defect_type", "severity", "customer_impact"],
      transcript_required: true,
    },
    input_payload: {
      brief: "Summarize the customer issue and tag severity.",
    },
    output_payload: {
      summary: "Low-light blur impacting inspection confidence.",
      severity: "medium",
    },
    claimed_at: "2026-03-17T14:20:00Z",
    due_at: "2026-03-18T06:00:00Z",
    submitted_at: "2026-03-18T05:22:00Z",
    reviewed_at: null,
    completed_at: null,
  },
];

export const annotationRevisions: AnnotationRevision[] = [
  {
    id: "rev_atlas_1",
    annotation_task_id: "task_atlas_1",
    revision_no: 1,
    revision_kind: "draft",
    source_ai_result_id: "ai_ann_1",
    created_by_user_id: "user_annotator_1",
    labels: ["helmet", "vest"],
    content: {
      notes: "Worker 2 may be missing goggles.",
    },
    review_notes: null,
    confidence_score: 0.84,
    created_at: "2026-03-18T08:22:00Z",
  },
  {
    id: "rev_beacon_1",
    annotation_task_id: "task_beacon_1",
    revision_no: 1,
    revision_kind: "submission",
    source_ai_result_id: "ai_ann_2",
    created_by_user_id: "user_annotator_1",
    labels: ["defect_type", "severity"],
    content: {
      summary: "Low-light blur during QA capture.",
      customer_impact: "Reinspection required",
    },
    review_notes: "Awaiting reviewer confirmation.",
    confidence_score: 0.76,
    created_at: "2026-03-18T05:22:00Z",
  },
];

export const aiResults: AiResult[] = [
  {
    id: "ai_ann_1",
    workflow_run_id: "run_ann_1",
    coze_run_id: "coze_ann_1",
    result_type: "annotation_suggestion",
    status: "waiting_for_human",
    source_entity_type: "annotation_task",
    source_entity_id: "task_atlas_1",
    raw_payload: {
      labels: ["helmet", "vest", "goggles"],
      confidence: 0.64,
    },
    normalized_payload: {
      suggested_labels: ["helmet", "vest", "goggles"],
      warning: "low confidence on goggles",
    },
    reviewed_by_user_id: null,
    review_notes: null,
    reviewed_at: null,
    applied_by_user_id: null,
    applied_at: null,
  },
  {
    id: "ai_ann_2",
    workflow_run_id: "run_ann_3",
    coze_run_id: "coze_ann_2",
    result_type: "annotation_suggestion",
    status: "accepted",
    source_entity_type: "annotation_task",
    source_entity_id: "task_beacon_1",
    raw_payload: {
      summary: "Customer reports blur in low light.",
      severity: "medium",
    },
    normalized_payload: {
      summary: "Low-light blur impacting verification quality.",
      severity: "medium",
    },
    reviewed_by_user_id: "user_reviewer_2",
    review_notes: "Aligned to release QA guidelines.",
    reviewed_at: "2026-03-18T05:35:00Z",
    applied_by_user_id: "user_reviewer_2",
    applied_at: "2026-03-18T05:36:00Z",
  },
  {
    id: "ai_risk_1",
    workflow_run_id: "run_risk_1",
    coze_run_id: "coze_risk_1",
    result_type: "risk_strategy",
    status: "waiting_for_human",
    source_entity_type: "risk_alert",
    source_entity_id: "alert_atlas_1",
    raw_payload: {
      proposals: ["Escalate staffing", "Re-sequence night shift review"],
    },
    normalized_payload: {
      summary: "Two viable mitigation paths generated for backlog pressure.",
    },
    reviewed_by_user_id: null,
    review_notes: null,
    reviewed_at: null,
    applied_by_user_id: null,
    applied_at: null,
  },
];

export const riskSignals: RiskSignal[] = [
  {
    id: "signal_atlas_1",
    project_id: "proj_atlas",
    source_kind: "workflow",
    signal_type: "annotation_backlog",
    severity: 65,
    status: "active",
    title: "Night shift backlog increasing",
    description: "Queued safety tasks have grown 22% over the last 12 hours.",
    signal_payload: {
      backlog_delta: 22,
      review_bottleneck: "night_shift",
    },
    observed_at: "2026-03-18T07:30:00Z",
    created_by_user_id: "user_pm_1",
  },
  {
    id: "signal_atlas_2",
    project_id: "proj_atlas",
    source_kind: "workflow",
    signal_type: "coze_latency",
    severity: 95,
    status: "active",
    title: "Annotation assist latency spike",
    description: "Two annotation runs breached the Coze callback window.",
    signal_payload: {
      delayed_runs: 2,
      average_delay_minutes: 17,
    },
    observed_at: "2026-03-18T08:02:00Z",
    created_by_user_id: "user_pm_1",
  },
  {
    id: "signal_beacon_1",
    project_id: "proj_beacon",
    source_kind: "review",
    signal_type: "quality_drift",
    severity: 60,
    status: "watch",
    title: "Reviewer disagreement increased",
    description: "Quality agreement dropped below the weekly threshold.",
    signal_payload: {
      agreement_rate: 0.82,
    },
    observed_at: "2026-03-18T06:40:00Z",
    created_by_user_id: "user_pm_2",
  },
];

export const riskAlerts: RiskAlert[] = [
  {
    id: "alert_atlas_1",
    project_id: "proj_atlas",
    risk_signal_id: "signal_atlas_1",
    status: "active",
    severity: 65,
    title: "Backlog pressure on Atlas",
    summary: "Review throughput is behind incoming volume for the current shift.",
    assigned_to_user_id: "user_pm_1",
    detected_by_workflow_run_id: "run_risk_1",
    next_review_at: "2026-03-18T12:00:00Z",
    resolved_at: null,
  },
  {
    id: "alert_atlas_2",
    project_id: "proj_atlas",
    risk_signal_id: "signal_atlas_2",
    status: "escalated",
    severity: 95,
    title: "Callback recovery needed",
    summary: "AI-assisted annotation runs are waiting on polling fallback.",
    assigned_to_user_id: "user_pm_1",
    detected_by_workflow_run_id: "run_ann_2",
    next_review_at: "2026-03-18T10:15:00Z",
    resolved_at: null,
  },
  {
    id: "alert_beacon_1",
    project_id: "proj_beacon",
    risk_signal_id: "signal_beacon_1",
    status: "active",
    severity: 60,
    title: "Reviewer disagreement trend",
    summary: "Quality review needs calibration before the next release batch.",
    assigned_to_user_id: "user_pm_2",
    detected_by_workflow_run_id: "run_risk_2",
    next_review_at: "2026-03-18T14:30:00Z",
    resolved_at: null,
  },
];

export const riskStrategies: RiskStrategy[] = [
  {
    id: "strategy_atlas_1",
    risk_alert_id: "alert_atlas_1",
    project_id: "proj_atlas",
    source_ai_result_id: "ai_risk_1",
    status: "proposed",
    proposal_order: 1,
    title: "Shift reviewer coverage earlier",
    summary: "Move one reviewer to the queue spike window for the next 8 hours.",
    strategy_payload: {
      owner: "review_ops",
      expected_effect: "reduce waiting_for_human queue by 20%",
    },
    approved_by_user_id: null,
    approved_at: null,
    applied_at: null,
  },
  {
    id: "strategy_atlas_2",
    risk_alert_id: "alert_atlas_1",
    project_id: "proj_atlas",
    source_ai_result_id: "ai_risk_1",
    status: "proposed",
    proposal_order: 2,
    title: "Temporarily prioritize image tasks",
    summary: "Reduce review variance by narrowing the task mix until backlog clears.",
    strategy_payload: {
      owner: "project_manager",
      expected_effect: "faster triage with fewer context switches",
    },
    approved_by_user_id: null,
    approved_at: null,
    applied_at: null,
  },
];

export const workflowRuns: WorkflowRun[] = [
  {
    id: "run_ann_1",
    organization_id: organizationId,
    project_id: "proj_atlas",
    workflow_domain: "annotation",
    workflow_type: "ai_assist_generate",
    source_entity_type: "annotation_task",
    source_entity_id: "task_atlas_1",
    status: "waiting_for_human",
    priority: 90,
    requested_by_user_id: "user_annotator_1",
    source: "frontend",
    correlation_key: "atlas-task-1",
    idempotency_key: "idem-ann-1",
    retry_of_run_id: null,
    input_snapshot: {
      task_type: "ppe_detection",
    },
    result_summary: {
      ai_result_status: "waiting_for_human",
    },
    error_code: null,
    error_message: null,
    started_at: "2026-03-18T08:11:00Z",
    completed_at: null,
    canceled_at: null,
    steps: [
      {
        id: "step_ann_1_validate",
        workflow_run_id: "run_ann_1",
        step_key: "validate",
        sequence_no: 1,
        status: "succeeded",
        attempt_count: 1,
        input_payload: {},
        output_payload: {
          validation: "ok",
        },
        last_error_code: null,
        last_error_message: null,
        started_at: "2026-03-18T08:11:00Z",
        completed_at: "2026-03-18T08:11:05Z",
      },
      {
        id: "step_ann_1_dispatch",
        workflow_run_id: "run_ann_1",
        step_key: "dispatch_to_coze",
        sequence_no: 2,
        status: "succeeded",
        attempt_count: 1,
        input_payload: {},
        output_payload: {
          dispatched: true,
        },
        last_error_code: null,
        last_error_message: null,
        started_at: "2026-03-18T08:11:05Z",
        completed_at: "2026-03-18T08:11:10Z",
      },
      {
        id: "step_ann_1_review",
        workflow_run_id: "run_ann_1",
        step_key: "human_review",
        sequence_no: 3,
        status: "waiting_for_human",
        attempt_count: 1,
        input_payload: {},
        output_payload: {},
        last_error_code: null,
        last_error_message: null,
        started_at: "2026-03-18T08:11:10Z",
        completed_at: null,
      },
    ],
    coze_runs: [
      {
        id: "coze_ann_1",
        workflow_run_id: "run_ann_1",
        step_id: "step_ann_1_dispatch",
        coze_workflow_key: "annotation-assist-v1",
        status: "completed",
        idempotency_key: "idem-ann-1",
        external_run_id: "coze-9001",
        attempt_no: 1,
        request_payload: {
          source_asset_id: "asset_atlas_img_1",
        },
        response_payload: {
          accepted: true,
        },
        callback_payload: {
          completed: true,
        },
        http_status: 202,
        dispatched_at: "2026-03-18T08:11:06Z",
        acknowledged_at: "2026-03-18T08:11:07Z",
        completed_at: "2026-03-18T08:11:17Z",
        last_polled_at: "2026-03-18T08:11:18Z",
      },
    ],
    ai_results: [],
  },
  {
    id: "run_ann_2",
    organization_id: organizationId,
    project_id: "proj_atlas",
    workflow_domain: "annotation",
    workflow_type: "ai_assist_generate",
    source_entity_type: "annotation_task",
    source_entity_id: "task_atlas_2",
    status: "running",
    priority: 60,
    requested_by_user_id: "user_pm_1",
    source: "frontend",
    correlation_key: "atlas-task-2",
    idempotency_key: "idem-ann-2",
    retry_of_run_id: null,
    input_snapshot: {
      task_type: "unsafe_motion_review",
    },
    result_summary: {
      last_stage: "polling_reconcile",
    },
    error_code: null,
    error_message: null,
    started_at: "2026-03-18T08:03:00Z",
    completed_at: null,
    canceled_at: null,
    steps: [
      {
        id: "step_ann_2_validate",
        workflow_run_id: "run_ann_2",
        step_key: "validate",
        sequence_no: 1,
        status: "succeeded",
        attempt_count: 1,
        input_payload: {},
        output_payload: {},
        last_error_code: null,
        last_error_message: null,
        started_at: "2026-03-18T08:03:00Z",
        completed_at: "2026-03-18T08:03:04Z",
      },
      {
        id: "step_ann_2_dispatch",
        workflow_run_id: "run_ann_2",
        step_key: "dispatch_to_coze",
        sequence_no: 2,
        status: "running",
        attempt_count: 1,
        input_payload: {},
        output_payload: {
          recovery_mode: "polling",
        },
        last_error_code: null,
        last_error_message: null,
        started_at: "2026-03-18T08:03:04Z",
        completed_at: null,
      },
    ],
    coze_runs: [
      {
        id: "coze_ann_3",
        workflow_run_id: "run_ann_2",
        step_id: "step_ann_2_dispatch",
        coze_workflow_key: "annotation-assist-v1",
        status: "running",
        idempotency_key: "idem-ann-2",
        external_run_id: "coze-9002",
        attempt_no: 1,
        request_payload: {
          source_asset_id: "asset_atlas_vid_1",
        },
        response_payload: {
          accepted: true,
        },
        callback_payload: {},
        http_status: 202,
        dispatched_at: "2026-03-18T08:03:05Z",
        acknowledged_at: "2026-03-18T08:03:06Z",
        completed_at: null,
        last_polled_at: "2026-03-18T08:19:00Z",
      },
    ],
    ai_results: [],
  },
  {
    id: "run_ann_3",
    organization_id: organizationId,
    project_id: "proj_beacon",
    workflow_domain: "annotation",
    workflow_type: "ai_assist_generate",
    source_entity_type: "annotation_task",
    source_entity_id: "task_beacon_1",
    status: "succeeded",
    priority: 60,
    requested_by_user_id: "user_annotator_1",
    source: "frontend",
    correlation_key: "beacon-task-1",
    idempotency_key: "idem-ann-3",
    retry_of_run_id: null,
    input_snapshot: {
      task_type: "issue_summary",
    },
    result_summary: {
      ai_result_status: "accepted",
    },
    error_code: null,
    error_message: null,
    started_at: "2026-03-18T05:12:00Z",
    completed_at: "2026-03-18T05:36:00Z",
    canceled_at: null,
    steps: [
      {
        id: "step_ann_3_validate",
        workflow_run_id: "run_ann_3",
        step_key: "validate",
        sequence_no: 1,
        status: "succeeded",
        attempt_count: 1,
        input_payload: {},
        output_payload: {},
        last_error_code: null,
        last_error_message: null,
        started_at: "2026-03-18T05:12:00Z",
        completed_at: "2026-03-18T05:12:03Z",
      },
      {
        id: "step_ann_3_apply",
        workflow_run_id: "run_ann_3",
        step_key: "apply_result",
        sequence_no: 2,
        status: "succeeded",
        attempt_count: 1,
        input_payload: {},
        output_payload: {
          revision_created: true,
        },
        last_error_code: null,
        last_error_message: null,
        started_at: "2026-03-18T05:35:00Z",
        completed_at: "2026-03-18T05:36:00Z",
      },
    ],
    coze_runs: [
      {
        id: "coze_ann_2",
        workflow_run_id: "run_ann_3",
        step_id: "step_ann_3_apply",
        coze_workflow_key: "annotation-assist-v1",
        status: "completed",
        idempotency_key: "idem-ann-3",
        external_run_id: "coze-8120",
        attempt_no: 1,
        request_payload: {
          source_asset_id: "asset_beacon_audio_1",
        },
        response_payload: {
          accepted: true,
        },
        callback_payload: {
          completed: true,
        },
        http_status: 200,
        dispatched_at: "2026-03-18T05:12:04Z",
        acknowledged_at: "2026-03-18T05:12:05Z",
        completed_at: "2026-03-18T05:34:52Z",
        last_polled_at: "2026-03-18T05:35:00Z",
      },
    ],
    ai_results: [],
  },
  {
    id: "run_risk_1",
    organization_id: organizationId,
    project_id: "proj_atlas",
    workflow_domain: "risk",
    workflow_type: "strategy_generate",
    source_entity_type: "risk_alert",
    source_entity_id: "alert_atlas_1",
    status: "waiting_for_human",
    priority: 90,
    requested_by_user_id: "user_pm_1",
    source: "frontend",
    correlation_key: "atlas-risk-1",
    idempotency_key: "idem-risk-1",
    retry_of_run_id: null,
    input_snapshot: {
      alert_id: "alert_atlas_1",
    },
    result_summary: {
      proposals_generated: 2,
    },
    error_code: null,
    error_message: null,
    started_at: "2026-03-18T07:33:00Z",
    completed_at: null,
    canceled_at: null,
    steps: [
      {
        id: "step_risk_1_ingest",
        workflow_run_id: "run_risk_1",
        step_key: "ingest_signal",
        sequence_no: 1,
        status: "succeeded",
        attempt_count: 1,
        input_payload: {},
        output_payload: {},
        last_error_code: null,
        last_error_message: null,
        started_at: "2026-03-18T07:33:00Z",
        completed_at: "2026-03-18T07:33:04Z",
      },
      {
        id: "step_risk_1_review",
        workflow_run_id: "run_risk_1",
        step_key: "human_review",
        sequence_no: 2,
        status: "waiting_for_human",
        attempt_count: 1,
        input_payload: {},
        output_payload: {},
        last_error_code: null,
        last_error_message: null,
        started_at: "2026-03-18T07:33:04Z",
        completed_at: null,
      },
    ],
    coze_runs: [
      {
        id: "coze_risk_1",
        workflow_run_id: "run_risk_1",
        step_id: "step_risk_1_ingest",
        coze_workflow_key: "risk-strategy-v1",
        status: "completed",
        idempotency_key: "idem-risk-1",
        external_run_id: "coze-9300",
        attempt_no: 1,
        request_payload: {
          alert_id: "alert_atlas_1",
        },
        response_payload: {
          accepted: true,
        },
        callback_payload: {
          completed: true,
        },
        http_status: 200,
        dispatched_at: "2026-03-18T07:33:05Z",
        acknowledged_at: "2026-03-18T07:33:07Z",
        completed_at: "2026-03-18T07:33:20Z",
        last_polled_at: "2026-03-18T07:33:22Z",
      },
    ],
    ai_results: [],
  },
  {
    id: "run_risk_2",
    organization_id: organizationId,
    project_id: "proj_beacon",
    workflow_domain: "risk",
    workflow_type: "strategy_generate",
    source_entity_type: "risk_alert",
    source_entity_id: "alert_beacon_1",
    status: "failed",
    priority: 60,
    requested_by_user_id: "user_pm_2",
    source: "frontend",
    correlation_key: "beacon-risk-1",
    idempotency_key: "idem-risk-2",
    retry_of_run_id: null,
    input_snapshot: {
      alert_id: "alert_beacon_1",
    },
    result_summary: {},
    error_code: "retryable_integration_error",
    error_message: "Coze callback not received within the reconciliation window.",
    started_at: "2026-03-18T06:10:00Z",
    completed_at: "2026-03-18T06:31:00Z",
    canceled_at: null,
    steps: [
      {
        id: "step_risk_2_dispatch",
        workflow_run_id: "run_risk_2",
        step_key: "dispatch_to_coze",
        sequence_no: 1,
        status: "failed",
        attempt_count: 2,
        input_payload: {},
        output_payload: {},
        last_error_code: "callback_missing",
        last_error_message: "Polling fallback exhausted the current retry window.",
        started_at: "2026-03-18T06:10:00Z",
        completed_at: "2026-03-18T06:31:00Z",
      },
    ],
    coze_runs: [],
    ai_results: [],
  },
];

export const auditEvents: AuditEvent[] = [
  {
    id: "audit_1",
    organization_id: organizationId,
    project_id: "proj_atlas",
    actor_user_id: "user_annotator_1",
    action: "annotation_task.claimed",
    reason_code: null,
    entity_type: "annotation_task",
    entity_id: "task_atlas_1",
    workflow_run_id: "run_ann_1",
    coze_run_id: null,
    request_id: "req_101",
    before_state: {
      status: "queued",
    },
    after_state: {
      status: "in_progress",
    },
    metadata: {},
    occurred_at: "2026-03-18T08:10:00Z",
  },
  {
    id: "audit_2",
    organization_id: organizationId,
    project_id: "proj_atlas",
    actor_user_id: "user_pm_1",
    action: "risk_alert.created",
    reason_code: "signal_triggered",
    entity_type: "risk_alert",
    entity_id: "alert_atlas_1",
    workflow_run_id: "run_risk_1",
    coze_run_id: null,
    request_id: "req_102",
    before_state: {},
    after_state: {
      status: "active",
    },
    metadata: {},
    occurred_at: "2026-03-18T07:33:00Z",
  },
  {
    id: "audit_3",
    organization_id: organizationId,
    project_id: "proj_beacon",
    actor_user_id: "user_reviewer_2",
    action: "ai_result.accepted",
    reason_code: null,
    entity_type: "ai_result",
    entity_id: "ai_ann_2",
    workflow_run_id: "run_ann_3",
    coze_run_id: "coze_ann_2",
    request_id: "req_103",
    before_state: {
      status: "waiting_for_human",
    },
    after_state: {
      status: "accepted",
    },
    metadata: {},
    occurred_at: "2026-03-18T05:35:00Z",
  },
  {
    id: "audit_4",
    organization_id: organizationId,
    project_id: "proj_beacon",
    actor_user_id: "user_pm_2",
    action: "workflow_run.failed",
    reason_code: "callback_missing",
    entity_type: "workflow_run",
    entity_id: "run_risk_2",
    workflow_run_id: "run_risk_2",
    coze_run_id: null,
    request_id: "req_104",
    before_state: {
      status: "running",
    },
    after_state: {
      status: "failed",
    },
    metadata: {},
    occurred_at: "2026-03-18T06:31:00Z",
  },
];

export const dashboardSummaries: DashboardSummary[] = projectSummaries.map(
  (project) => {
    const projectTasks = annotationTasks.filter(
      (task) => task.project_id === project.id,
    );
    const projectAlerts = riskAlerts.filter((alert) => alert.project_id === project.id);
    const projectRuns = workflowRuns.filter((run) => run.project_id === project.id);
    const projectActivity = [...auditEvents, ...aiResults]
      .filter((item) => {
        if ("project_id" in item) {
          return item.project_id === project.id;
        }

        const sourceTask = annotationTasks.find(
          (task) => task.id === item.source_entity_id && task.project_id === project.id,
        );
        const sourceAlert = riskAlerts.find(
          (alert) =>
            alert.id === item.source_entity_id && alert.project_id === project.id,
        );

        return Boolean(sourceTask ?? sourceAlert);
      })
      .sort((left, right) => {
        const leftTimestamp =
          "occurred_at" in left ? left.occurred_at : left.reviewed_at ?? "";
        const rightTimestamp =
          "occurred_at" in right ? right.occurred_at : right.reviewed_at ?? "";
        return rightTimestamp.localeCompare(leftTimestamp);
      })
      .slice(0, 4);

    return {
      project,
      queues: {
        annotation: projectTasks.filter((task) =>
          ["queued", "in_progress", "submitted"].includes(task.status),
        ).length,
        risk: projectAlerts.filter((alert) => alert.status !== "resolved").length,
      },
      workload: {
        active_runs: projectRuns.filter((run) =>
          ["queued", "running", "waiting_for_human"].includes(run.status),
        ).length,
        waiting_for_human: projectRuns.filter((run) => run.status === "waiting_for_human")
          .length,
        waiting_for_coze: projectRuns.filter((run) => run.status === "running").length,
        failures_last_24h: projectRuns.filter((run) => run.status === "failed").length,
      },
      inbox: {
        assigned_tasks: projectTasks.filter(
          (task) =>
            task.assigned_to_user_id === meResponse.user.id &&
            task.status !== "completed",
        ).length,
        open_alerts: projectAlerts.filter((alert) => alert.status !== "resolved").length,
        pending_approvals: projectRuns.filter((run) => run.status === "waiting_for_human")
          .length,
      },
      recent_activity: projectActivity,
    };
  },
);
